parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # User checker pour bloquer les propriétaires non approuvés
    App\Security\UserChecker:
        tags:
            - { name: security.user_checker }