# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  forum.openai_api_key_default: ""

  stripe_secret_key: "%env(resolve:STRIPE_SECRET_KEY)%"
  stripe_webhook_secret: "%env(resolve:STRIPE_WEBHOOK_SECRET)%"
  stripe_publishable_key: "%env(STRIPE_PUBLISHABLE_KEY)%"

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  App\Controller\:
    resource: "../src/Controller/"
    tags: ["controller.service_arguments"]

  App\Service\DislikeAlertMailer:
    arguments:
      $adminEmail: "%env(ADMIN_EMAIL)%"
      $mailerFrom: "%env(MAILER_FROM)%"

  App\Service\ForumAiAssistant:
    arguments:
      $apiKey: "%env(default:forum.openai_api_key_default:OPENAI_API_KEY)%"

  App\Command\TestMailCommand:
    arguments:
      $adminEmail: "%env(ADMIN_EMAIL)%"
      $mailerFrom: "%env(MAILER_FROM)%"

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
